(* let rec token buf = *)
(*   match%sedlex buf with *)
(*   | Plus Compl Utf8 "+† \t\r\n" -> Hymn_parser.SYLLABLE (Sedlexing.Utf8.lexeme buf) *)
(*   | Chars "+†" -> Hymn_parser.FLEX *)
(*   | "*" -> Hymn_parser.MEDIATOR *)
(*   | Plus Chars "\t " -> Hymn_parser.SPACE *)
(*   | Plus "\n" | Plus "\r\n" -> Hymn_parser.NEWLINE *)
(*   | "|" -> Hymn_parser.SEPARATOR *)
(*   | _ -> failwith ("Unexpected character: " ^ Sedlexing.Utf8.lexeme buf) (* TODO -- Make descriptive Message*) *)
